#!/bin/bash
# Quick Test Script for AI Service

echo "========================================="
echo "AI Service - Quick Test Guide"
echo "========================================="
echo ""
echo "1. Make sure dependencies are running:"
echo "   - MySQL on localhost:3306"
echo "   - RabbitMQ on localhost:5672"
echo "   - Eureka Server on localhost:8761"
echo ""
echo "2. Rebuild and restart the service:"
echo "   cd Fitness/ai-service"
echo "   mvn clean install"
echo "   mvn spring-boot:run"
echo ""
echo "3. Watch for these startup messages:"
echo "   ✓ Connected to MySQL database"
echo "   ✓ Connected to RabbitMQ"
echo "   ✓ Registered with Eureka"
echo "   ✓ RabbitMQ listener started"
echo ""
echo "4. Test by sending an activity message"
echo "   The service should:"
echo "   - Receive the activity from RabbitMQ"
echo "   - Call Gemini API successfully (no 404)"
echo "   - Generate recommendations"
echo "   - Log the response"
echo ""
echo "========================================="
echo "Expected Success Log Pattern:"
echo "========================================="
echo "INFO  - Processing activity: {id}"
echo "DEBUG - Calling Gemini API at: https://generativelanguage.googleapis.com/v1/models/gemini-1.5-flash:generateContent"
echo "INFO  - Generated Recommendation: {json response}"
echo ""
echo "========================================="
echo "If you see errors, check:"
echo "========================================="
echo "1. Gemini API Key is valid"
echo "2. Network can reach generativelanguage.googleapis.com"
echo "3. MySQL credentials are correct"
echo "4. RabbitMQ is accessible"
echo ""
